version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    expose:
      - "8000"
    volumes:
      - ./data:/app/data # persist SQLite database
    environment:
      - JWT_SECRET=${JWT_SECRET:-changeme}
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASS=${ADMIN_PASS:-changeme}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-fake}
    restart: unless-stopped

  web:
    build:
      context: ./website
      dockerfile: Dockerfile.web
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=/api
    depends_on:
      - api
    restart: unless-stopped

  proxy:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8001:80"
    depends_on:
      - api
      - web 